### ISSUE TITLE
Default parameter event in Atm_led.onFinish don't work

### ISSUE THREAD

**Issue by MrFroop** [tinkerspy/Automaton#18]
This could be a question or a bug report, it could also be an inconsistency between the code and the documentation. The wiki documentation for the led machines onFinish method, describes the event parameter to be EVT_BLINK if no value is given. The following example exists:

```c++
led1.begin( 4 ).blink( 500, 500, 3 ).onFinish( led2 );
led2.begin( 4 ).blink( 50, 50, 10 );
led1.trigger( led1.EVT_BLINK );
```
But looking at the code, and trying it out on an "Adafruit Feather 32u4 basic", I noticed that the default value is commented out and the above example won't work. I had to define the event or it just stopped after the first led.

```c++
led1.begin( 4 ).blink( 500, 500, 3 ).onFinish( led2, led1.EVT_BLINK);
led2.begin( 4 ).blink( 50, 50, 10 );
led1.trigger( led1.EVT_BLINK );
```
Is this the intended behavior? I compile my code on Linux using gcc-avr version 4.9.2

**Comment by tinkerspy** [comment]
Thanks for reporting that, it's an error in the documentation. The onFinish() method started its life as a way to chain different led patterns, so having EVT_BLINK as a default seemed to make sense then. Now it's just a standard connector and all connectors (on* methods) have 0 as the default event.

So your second code fragment is correct. Have you looked at the player machine for blink pattern generation? It can be pretty powerful as well.

I updated the Atm_led documentation.

Rgdz,
Tinkerspy
