### ISSUE TITLE
fader++

### ISSUE THREAD

**Issue by dvv** [tinkerspy/Automaton#26]
Hello!

Wonder if you could upgrade Atm_fade to fade between arbitrary values [X1..X2](X1, X2 both bytes), not only in full range [0..255]?

TIA,
--Vladimir

**Comment by tinkerspy** [comment]
Could you have a look at Yhfudev's work on Atm_fade and let me know if it does what you want?

https://github.com/tinkerspy/Automaton/pull/22

Rgdz,
Tinkerspy
