### ISSUE TITLE
Compilation error: 'connector' cannot appear in a constant-expression

### ISSUE THREAD

**Issue by jtroch** [tinkerspy/Automaton#31]
Hi,

I tried my first automaton project and compiled the following sample code

#include <Automaton.h>
Atm_timer timer;
void timer_callback( int idx, int v, int up ) {}
void setup() {
  timer.begin(1000)
    .repeat(ATM_COUNTER_OFF)
    .onTimer(timer_callback)
    .start();
}
void loop() {
  automaton.run();
}

Unfortunately, I get the following error during compilation:

**...Atm_controller.cpp: In member function 'bool Atm_controller::eval_one(atm_connector&)':
...Atm_controller.cpp:47:10: error: 'connector' cannot appear in a constant-expression
     case connector.REL_EQ:**

(And a lot more of similar errors)

What is the reason of this error ?

Thanks,
John

**Comment by tinkerspy** [comment]
It doesn't occur in my setup. It's been reported before, though. What's your setup? Which board are you using and what version of the IDE? Anyway, in the current version all the constant references have been changed like this:

```c++
    case connector::REL_EQ:
      return connector.pull() == connector.event;
```

changed to:

```c++
    case atm_connector::REL_EQ:
      return connector.pull() == connector.event;
```

So if you use the latest version of Automaton you should be OK. I'm guessing this is some C++ compiler version/setting problem.
