### ISSUE TITLE
Variable Generated by Acceptor Custom Machine Use in Sketch Outside of Callback?

### ISSUE THREAD

**Issue by Mike58501** [tinkerspy/Automaton#32]
TinkerSpy,

I know you are busy like the rest of us & I know I should be able to come up with the specific answer on my own .  I will try to be clear on a specific question about the specific Atm_acceptor machine that you graciously shared with me & others via a YouTube. [https://www.youtube.com/watch?v=vKqEeH4OvqU](url)

I really need to find a way when I am done using the acceptor machine within my Arduino sketch to have access to the specific v integer or credit integer outside of the callback. The purpose of that ability is so I can reassign a larger or lower number for the Atm_timer repeat variable (time countdown) depending on what specific credit or v was finalized from the Atm_acceptor acceptor machine.   For example if during the acceptance of coins the final amount is v == 8 to 9 range, it would need to have a different  predefined variable actual number for the specific repeat int arg than if it was in the v == 10 to 12 range etc.

Below are snippets of your code that I thought ??? would make it so the final v or credit integer would be available outside of the state machine but my sketch can't see it unless it stays within the confines of the below top snippet callback.  
~~~
void acceptor_callback( int idx, int v, int up ) {
do something based on the  v value here;
}

Atm_acceptor& Atm_acceptor::set( int v ) {
  credit = v;
  return *this;

int Atm_acceptor::state( void ) {
  return credit;
}
~~~

Thanks in advance,

Hopefully this will be the last snag that I will have to bother you &/or others about.

mike

**Comment by tinkerspy** [comment]
I thought that was in the example sketch:

```c++
        Atm_acceptor credit;

...

        Serial.print( "Credit is now: " );
        Serial.println( credit.state() );
```
The state() method will return the same value as the 'v' argument inside the onChange() handler.

Rgdz,
Tinkerspy
