### ISSUE TITLE
Global Variable derived from an Arduino Pin State help needed

### ISSUE THREAD

**Issue by Mike58501** [tinkerspy/Automaton#33]
Hi TinkerSpy or other farther along Automaton person,

Can you share an Automaton specific guideline or suggestion when it comes to generating an integer variable that can be used in a Global way.  The integer would need to be based on whether an Arduino pin is HIGH or LOW.

For example:  If I declare    int test = 2;   in the sketch above the void setup () ..... I have no problem putting in (acceptor.state - test) for the repeat method of a timer countdown that is within the acceptor callback.  It will then see the repeat number as the result of the acceptor.state minus the whole number. both compiling & functioning.   The problem is that I need the test variable to be = 0 when a specific pin changes to LOW.  The challenge is to make it so that change can be seen ... ideally within anywhere of the void setup () including within custom callback code such as within the custom Acceptor State Machine callback code that you helped me with.

I honestly did try to see examples of this specific use of an int variable & so far I am not seeing this kind of availability of a needed declared integer number derived from a potentially changiing HIGH or LOW state of an Arduino Uno pin.

Could you run some tests to see if what I described above is even possible within Automaton?  

Thanks

Mike

**Comment by tinkerspy** [comment]
Why would you use a global variable if you can just call ```digitalRead( PIN_NUMBER );``` anywhere in your code and get the current state of the pin?


```c++

int test() {
  if ( digitalRead( PIN_NUMBER ) ) {
    return 2;
  } else {
    return 0;
  }
}

```

Of course you could use an Atm_digital machine if you really insist on changing the global variable 'live':

```c++
#include <Automaton.h>

#define PIN_NUMBER 4
int test = 2;

Atm_digital dig;

void setup() {

  dig.begin( PIN_NUMBER, 20 ) // 20 ms debounce
    .onChange( HIGH, []( int idx, int v, int up ) {
        if ( v ) {
          test = 2;
        } else {
          test = 0;
        }
    } );

}
```

And even then you'd probably be better off calling ```dig.state()``` instead.

```c++

int test() {
  if ( dig.state() ) {
    return 2;
  } else {
    return 0;
  }
}

```
