### ISSUE TITLE
Baby steps for helping Automaton low memory situation?

### ISSUE THREAD

**Issue by Mike58501** [tinkerspy/Automaton#36]
Tinkerspy &/or other astute programmer,

In my project I am not seeing an outer need for putting args or parameters with my custom wasco machine in my final sketch.  I am doing it based on my humble attempts to follow your creation of your two custom machine examples blink_modular, & trafficlight.

The reason why I am asking is because I am looking for ways to not have something publicly declared to save on scarce dynamic memory.  

Can you elaborate on some situations where  the following lines in my cpp & h files can be improved upon to help dynamic memory.  I am using only 57% of the prog mem whereas I am using 90% of the dynamic memory at this very close to final point.  That even with commenting out the "wasco.trace( Serial );" & the other interacting machines' serial monitor trace also.

In .h file under public:
~~~
    Atm_wasco& begin(int pin4, int pin5, int pin6, int pin7, int pin9, int pin10, int pin11, int pin12, int pin14, int pin15, int pin16);
~~~
In .h file under private:
~~~
    int pin4, pin5, pin6, pin7, pin9, pin10, pin11, pin12, pin14, pin15, pin16;
~~~

In .cpp file:
~~~
Atm_wasco& Atm_wasco::begin(int pin4, int pin5, int pin6, int pin7, int pin9, int pin10, int pin11, int pin12, int pin14, int pin15, int pin16) {
  // clang-format off

  Machine::begin( state_table, ELSE );
  this->pin4 = pin4;
  this->pin5 = pin5;
  this->pin6 = pin6;
  this->pin7 = pin7;
  this->pin9 = pin9;
  this->pin10 = pin10;
  this->pin11 = pin11;
  this->pin12 = pin12;
  this->pin14 = pin14;
  this->pin15 = pin15;
  this->pin16 = pin16;
  timer.set(3000);
  pinMode (pin4, OUTPUT);
  pinMode (pin5, OUTPUT);
  pinMode (pin6, OUTPUT);
  pinMode (pin15, OUTPUT);
  pinMode (pin16, OUTPUT);
  pinMode (pin7, INPUT_PULLUP);
  pinMode (pin9, INPUT_PULLUP);
  pinMode (pin10, INPUT_PULLUP);
  pinMode (pin11, INPUT_PULLUP);
  pinMode (pin12, INPUT_PULLUP);
  pinMode (pin14, INPUT_PULLUP);  
  return *this;
~~~

If anyone can provide helpful suggestions along the line of correcting what is not needed Automaton-Wise to be declared public &/or if "int" should be changed to "byte" or whatever ... I & others would appreciate it.

Mike

**Comment by tinkerspy** [comment]
Using a byte or char instead of int would some a tiny bit of memory.
