### ISSUE TITLE
Atm_command and cmdlist in PROGMEM

### ISSUE THREAD

**Issue by IW3IJQ** [tinkerspy/Automaton#37]
The command list for Atm_command is generally defined as:

const char cmdlist[] = 

If I try to move it to progmem to save ram:

const char cmdlist[] PROGMEM = 

Atm_command no longer work. The v parameter in callback is always 0xFFFF

**Comment by tinkerspy** [comment]
It doesn't work that way. You need to use a special instruction to access the PROGMEM memory: pgm_read_byte_near( addr ).
