### ISSUE TITLE
Atm_button onPress callback and parameter its not defined in Library

### ISSUE THREAD

**Issue by antonioabb** [tinkerspy/Automaton#4]
In manual:
Alternatively pass an idx parameter to the callback to reuse a single callback for multiple Atm_button
<pre>
void btn_change( int press, int idx ) 
{
  if ( press ) {
    if ( idx == 1 ) led1.toggle( led1.IDLE, led1.START );
    if ( idx == 2 ) led2.toggle( led2.IDLE, led2.START );
  }
}

void setup() 
{
  btn.begin( 11 ).onPress( btn_change, 1 );
  btn.begin( 12 ).onPress( btn_change, 2 );
}
</pre>

**Comment by tinkerspy** [comment]
Hi Antonio,

I assume you're using the release version. If you clone the master branch with git you'll get the version with the callback that has the idx argument.

Regards,
Tinkerspy
