### ISSUE TITLE
tone/noTone is not available for Due

### ISSUE THREAD

**Issue by vermut** [tinkerspy/Automaton#41]
https://travis-ci.org/MysteriaLV/boxes/builds/224787770

Maybe Atm_player.* shouldn't be included at all when `#ifdef _VARIANT_ARDUINO_DUE_X_` ?

P.S. Love your lib. Real life saver. Thanks.

**Comment by Mike58501** [comment]
That is interesting that TinkerSpy's Automaton is being used some for Arduino Due.  Has anyone used & tested Automaton for the Arduino MEGA 1280 2560?  The Mega certainly could make lack of memory problems less likely ... if there are not other issues besides just paying attention to the extra IO.

**Comment by rawtaz** [comment]
What's so interesting about it?I use Automaton on a Mega 2560 because it has more memory than the Leonardo. It works great.

**Comment by tinkerspy** [comment]
It should work on all Arduino supported platforms, at least that's what I aim for. It works fine on the teensy range or on the esp8266 as well.

Vermut, is that the Duemilanove I see in the Arduino IDE? Because it seems to compile fine with that setting. Atm_player has more functionality than just controlling a speaker, so I would prefer to just conditionally disable the (no)tone command if that would be necessary.

**Comment by vermut** [comment]
Duemilanove and Due are different things :) I also got confused first.

Here is a short disambiguation: http://platformio.org/boards?filter%5Bframeworks%5D=arduino&filter%5Bname%5D=due

conditionally disabling the (no)tone is fine. 
or even better -  emulating it: http://forum.arduino.cc/index.php/topic,136500.0.html

**Comment by tinkerspy** [comment]
Hi Vermut,

I finally implemented the ifdefs in the master branch.
Could you let me know if it fixes your problems.

Sorry for the delay.

Regards,
Tinkerspy

**Comment by vermut** [comment]
Still failing. You sure *ifdef* is correct pragma? Seems like you disabled _tone_ for all platforms except DUE.

**Comment by tinkerspy** [comment]
Yeah, looks like I got the conditional the other way around. Now, that never happened to me before ;-)

Is it OK now?

**Comment by vermut** [comment]
Yes, much better: https://travis-ci.org/MysteriaLV/boxes/builds/234074868

**Comment by vermut** [comment]
Please bump library.json so Platformio will pick up new changes.

**Comment by rfestag** [comment]
I'm running into the same issue with my Bluefruit feather (ARDUINO_FEATHER52).

**Comment by tinkerspy** [comment]
I fixed it in the latest master, can you check if it works for you?

Rgdz, Tinkerspy

**Comment by rfvermut** [comment]
Many library managers are not noticing those changes. Please bump the version - #46
