### ISSUE TITLE
Atm_button BTN_PASS4 = -2

### ISSUE THREAD

**Issue by kaminet** [tinkerspy/Automaton#49]
Hello!

I was analysing Atm_button to learn from it (I'm not a real programmer).
There is declaration in header file:
`enum { BTN_PASS4 = -2, BTN_PASS3 = -3, BTN_PASS2 = -2, BTN_PASS1 = -1, BTN_RELEASE = 0, BTN_PRESS1 = 1, BTN_PRESS2 = 2, BTN_PRESS3 = 3, BTN_PRESS4 = 4 };
`
I think there should be `BTN_PASS4 = -4` ?

**Comment by tinkerspy** [comment]
It certainly should. 
Thanks for catching that, I'll get it fixed!

Regards,
Peter


On Thu, Nov 9, 2017, at 12:26 AM, kaminet wrote:
> Hello!


> I was analysing Atm_button to learn from it (I'm not a real
> programmer).>  There is declaration in header file:
> enum { BTN_PASS4 = -2, BTN_PASS3 = -3, BTN_PASS2 = -2, BTN_PASS1 = -1,
> BTN_RELEASE = 0, BTN_PRESS1 = 1, BTN_PRESS2 = 2, BTN_PRESS3 = 3,
> BTN_PRESS4 = 4 };>  I think there should be BTN_PASS4 = -4 ?


> — You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub[1], or mute the
> thread[2].> 


Links:

  1. https://github.com/tinkerspy/Automaton/issues/49
