### ISSUE TITLE
Inverted Buttons

### ISSUE THREAD

**Issue by ddownn** [tinkerspy/Automaton#58]
I am using a hardware debouncing circuit like this using a Hex Schmitt-Trigger Inverter:

<img width="405" alt="image" src="https://user-images.githubusercontent.com/40695558/42606232-5d8f1288-854a-11e8-9293-d4265f46cee8.png">

As a result, the buttons are effectively inversed with the "Automaton button machine." 

What would be the best way to account for the inversion caused by the SN74HC14 in Automaton code so that button presses and releases can be recognized correctly? 

Is there some way to just flip what defines a button as "Pressed"

**Comment by tinkerspy** [comment]
No, not in the button machine. But the Atm_digital machine provides the same basic functionality and also has an activeLow setting that should provide what you want. It has more flexibilty in the pin handling than Atm_button, you can also enable and disable pullups and software debouncing.

**Comment by ddownn** [comment]
Ah, yes. Thank you
