### ISSUE TITLE
When exactly Arduino is put to sleep mode?

### ISSUE THREAD

**Issue by adamryczkowski** [tinkerspy/Automaton#6]
I can't see any invocation of the `sleep_mode()` or any other function. Are you sure, that putting Arduino to sleep is supported by this library? Or should I do it manually? If so, what is the purpose of the `Machine::sleep` member variable?

**Comment by tinkerspy** [comment]
Hi Adam,

The Automaton sleep mode allows you to put state machines to sleep. A sleeping state machine's event loop is not executed. That saves processor cycles but it doesn't put the micro controller to sleep. The non-sleeping state machines keep running at full speed. It doesn't save power but it allows you to distribute the processor cycles over the running machines more effectively. 

So I guess you should do it manually. ;-)

Do you have any ideas how it could be integrated?

Regards,
Tinkerspy
