### ISSUE TITLE
Consider Using ArduBadge

### ISSUE THREAD

**Issue by gilmaimon** [tinkerspy/Automaton#63]
Hi :)
Consider using ArduBadge as an addition to the readme :)
For Automaton it will look like this:
[![arduino-library-badge](https://www.ardu-badge.com/badge/Automaton.svg)](https://www.ardu-badge.com/Automaton)
Markdown:
`[![arduino-library-badge](https://www.ardu-badge.com/badge/Automaton.svg)](https://www.ardu-badge.com/Automaton)`
Notice how the badge shows green (signaling that the Automaton is on the Library Manager) and it also points out the latest version. Clicking on the badge opens up a custom installation page for Automaton and even a link to a ZIP file of the latest version (with explanation on how to install that zip file).

Hope you liked it =)

**Comment by tinkerspy** [comment]
I consider this spam and therefore I will not use it.
