### ISSUE TITLE
Machine template editor is down

### ISSUE THREAD

**Issue by UladzimirKapylou** [tinkerspy/Automaton#64]
Hi!

Thank you for such a cool library. But it seems, that your Machine template editor is down now. I'm not sure, maybe it will recover itself soon. Or maybe you need to do same action. Just a note for you.
And just a hope for me)

Regards.

**Comment by tinkerspy** [comment]
Thanks for the warning. The IP address of the server has changed. I've requested a DNS change to correct this issue. It might take a while though...

**Comment by tinkerspy** [comment]
It's up again. I put it on a static IP now, so it should be much more stable.

**Comment by UladzimirKapylou** [comment]
That works. Thank you so much! It is a really helpful tool.

**Comment by mnolletti69** [comment]
The site is down since almost three day.

**Comment by tinkerspy** [comment]
Yeah, I know, I'm sorry, I was struggling with my load balancer. 
Good news is, you msg made me try it one more time and now it appears to work :-)

I also added a monitoring entry on https://statuscake.com so I'll know when things fail in the future.
