### ISSUE TITLE
0b vs B

### ISSUE THREAD

**Issue by HaxorGate** [tinkerspy/Automaton#70]
Just a tiny point. You might want to consider changing the instances of the 'B' binary macros to the GCC-supported '0b' notation. I came across the three (I think) files that use the Arduino macro for binary when I was working with this library on the Sparkfun Redboard Artemis ATP (i.e. a third-party board without the 'B' macro). Changing the files got it to compile just fine (I can't recall which ones they are; sorry).

**Comment by jpdupays** [comment]
Fixed that.

Thanks,
Tinkerspy

**Comment by tinkerspy** [comment]
Fixed that.

Tinkerspy
